function main() {
    throw("This is an exception thrown from within PrePro!");
}
